name: Build Service

on:
  workflow_dispatch:
  pull_request:
    paths-ignore: ['*.md']
    branches: ['main', 'master']
  push:
    paths-ignore: ['*.md']
    branches: ['main', 'master']

jobs:
  BuildPackage:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare StartOS SDK
        uses: Start9Labs/sdk@v1

      - name: Checkout services repository
        uses: actions/checkout@v4

      - name: Build the service package
        id: build
        run: |
          git submodule update --init --recursive
          start-sdk init
          make
          PACKAGE_ID=$(yq -oy ".id" manifest.*)
          echo "::set-output name=package_id::$PACKAGE_ID"
        shell: bash

      - name: Upload .s9pk
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.package_id }}.s9pk
          path: ./${{ steps.build.outputs.package_id }}.s9pk